run: { timeout: 3m }

linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 0.5
    skip-tests: false

  govet:
    check-shadowing: true
    enable-all: true

  misspell: { locale: US }

  depguard:
    rules:
      main: { allow: ["$gostd", "github.com/BooleanCat/go-functional"] }

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - depguard
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gocritic
    - gosec
    - nilerr
    - gofmt
    - gocyclo
    - misspell
